### ISSUE TITLE
there might be a bug

### ISSUE THREAD

**Issue by alingse** [berkerpeksag/selectors34#5] opened 2017-01-18 13:19 UTC
I got some exception while use kafka-python

```python
  File "/usr/local/lib/python2.7/dist-packages/kafka/selectors34.py", line 340, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
TypeError: select() takes at most 4 arguments (5 given)
```

```python
    if sys.platform == 'win32':
        def _select(self, r, w, _, timeout=None):
            r, w, x = select.select(r, w, w, timeout)
            return r, w + x, []
    else:
        _select = select.select
```

If the sys.platform is not 'win32', `self._select` will be `select.select`

and there will add one more argument `self`
I saw gevent use like this

```python
        if selectors.SelectSelector._select in (select.select, orig_select_select):
            def _select(self, *args, **kwargs):
                return select.select(*args, **kwargs)
            selectors.SelectSelector._select = _select
```

and there, the code can be this:

```python
    if sys.platform == 'win32':
        def _select(r, w, _, timeout=None):
            r, w, x = select.select(r, w, w, timeout)
            return r, w + x, []
    else:
        def _select(self, *args, **kwargs):
            return select.select(*args, **kwargs)
```

hope your reply.

**Comment by berkerpeksag** [comment] 2017-01-18 16:25
Thanks for the report. This looks like the same problem in https://github.com/berkerpeksag/selectors34/pull/4. Do you have a snippet to reproduce the traceback you've pasted above?

**Comment by berkerpeksag** [comment] 2017-01-21 04:13
This is now fixed by https://github.com/berkerpeksag/selectors34/commit/6128e067bcd0cc7e280d673c6eb14c3c754863d8.

**Closed as completed by berkerpeksag** 2017-01-21 04:13 UTC
